### ISSUE TITLE
Running this on Mac M1 gives error... 

### ISSUE THREAD

**Issue by enzyme69** [bryandlee/animegan2-pytorch#13]
Hi Bryan, I wanted to make this to work locally on my machine, so I don't need to queue, but I kept getting error when running: **python convert_weights.py**:

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/animegan2-pytorch-main-2/convert_weights.py", line 7, in <module>
    from AnimeGANv2.net import generator as tf_generator
  File "/Users/jimmygunawan/animegan2-pytorch-main-2/AnimeGANv2/net/generator.py", line 1, in <module>
    import tensorflow.contrib as tf_contrib
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

I am not programmer, so far I did try to install tensorflow via miniforge on this Mac machine, I think I also have conda stuff and tensorflow installed, but issue above persist.

Any idea how to fix this? Thanks!

**Comment by enzyme69** [comment]
If I skip that "conversion" step, I get error:
```
(base) jimmygunawan@192-168-1-106 animegan2-pytorch-main-2 % python test.py --input_dir /faces --device cpu
Traceback (most recent call last):
  File "/Users/jimmygunawan/animegan2-pytorch-main-2/test.py", line 89, in <module>
    test(args)
  File "/Users/jimmygunawan/animegan2-pytorch-main-2/test.py", line 33, in test
    net.load_state_dict(torch.load(args.checkpoint, map_location="cpu"))
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pytorch_generator_Paprika.pt'
```

**Comment by enzyme69** [comment]
Ok, the next thing I did was simply to use "pytorch_generator_Paprika.pt" that you provided. I get a result with "cpu" which is nice. But with M1 and supported "tensorflow 2" metal gpu, I wonder if this can be faster?

**Comment by bryandlee** [comment]
Hi, you might want to check out [the tensor implementation](https://github.com/TachibanaYoshino/AnimeGANv2). As far as I know, the accelerated computing with pytorch on M1 is not supported yet.

**Comment by enzyme69** [comment]
Ok thanks Bryand!
