### ISSUE TITLE
how convert video to anime？

### ISSUE THREAD

**Issue by CongYuSanXun** [bryandlee/animegan2-pytorch#8]
Can you add the code? Thanks in advance!

**Comment by bryandlee** [comment]
Hi, you can extract and convert each frame from a video.

```python
import cv2

video_path = "video.mp4"

video_in = cv2.VideoCapture(video_path)

fps = int(video_in.get(cv2.CAP_PROP_FPS))
width = video_in.get(cv2.CAP_PROP_FRAME_WIDTH)
height = video_in.get(cv2.CAP_PROP_FRAME_HEIGHT)
fourcc = cv2.VideoWriter_fourcc(*"MP4V")
video_out = cv2.VideoWriter("video_out.mp4", fourcc, fps, (width, height))

while True:
    ret, frame = video_in.read()
    if not ret:
        break

    frame = torch.from_numpy(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).float() / 127.5 - 1.0
    out = net(frame)
    out = (out * 127.5 + 127.5).clip(0, 255).numpy().astype(np.uint8)
    out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)
    video_out.write(out)

video_in.release()
video_out.release()

```

**Comment by CongYuSanXun** [comment]
ohhhhh，thanks.

**Comment by dklymenk** [comment]
Hi, I have tried to test the code snippet above and couldn't get it to work. After adding missing imports, initializing `net` and adding missing `)`  on this line 
```python
frame = torch.from_numpy(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).float() / 127.5 - 1.0
```
I have this going:
```python
import cv2
import torch
import numpy as np

from model import Generator

video_path = "video.mp4"

video_in = cv2.VideoCapture(video_path)

fps = int(video_in.get(cv2.CAP_PROP_FPS))
width = int(video_in.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video_in.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc = cv2.VideoWriter_fourcc(*"MP4V")
video_out = cv2.VideoWriter("video_out.mp4", fourcc, fps, (width, height))

device = 'cpu'
net = Generator()
net.load_state_dict(torch.load(f"face_paint_512_v2_0.pt", map_location="cpu"))
net.to(device).eval()

while True:
    ret, frame = video_in.read()
    if not ret:
        break

    frame = torch.from_numpy(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)).float() / 127.5 - 1.0
    out = net(frame)
    out = (out * 127.5 + 127.5).clip(0, 255).numpy().astype(np.uint8)
    out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)
    video_out.write(out)

video_in.release()
video_out.release()

```

When running it I have this error:
```
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "video.py", line 28, in <module>
    out = net(frame)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dklymenk/Documents/animegan2-pytorch/model.py", line 91, in forward
    out = self.block_a(input)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/modules/padding.py", line 170, in forward
    return F.pad(input, self.padding, 'reflect')
  File "/home/dklymenk/miniconda3/envs/tf1.15/lib/python3.7/site-packages/torch/nn/functional.py", line 3557, in _pad
    assert len(pad) == 2, '3D tensors expect 2 values for padding'
AssertionError: 3D tensors expect 2 values for padding
```

Is something wrong with my environment or did I do something wrong while filling the blanks in the code above?

Both the test.py and the jupyter notebook are running flawlessly.

**Comment by bryandlee** [comment]
The snippet is not meant to be run as is, but try this

```python
frame = torch.from_numpy(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)).float() / 127.5 - 1.0
frame = frame.permute(2,1,0).unsqueeze(0)  # add this
out = net(frame)
out = out.squeeze(0).permute(1,2,0)  # and this
out = (out * 127.5 + 127.5).clip(0, 255).numpy().astype(np.uint8)
```

and you might also wanna disable the gradient computation
```python
torch.set_grad_enabled(False)  
```

**Comment by dklymenk** [comment]
Thank you. With those changes the code runs, however, the resulting mp4 file has no streams. So I am unable to play it.

It was converting a 7 second video for about 2 hours, so I would assume the script was doing actual work, it just wasn't able to save it properly.

**Comment by TachibanaYoshino** [comment]
#21 Here is the video to animation script I gave.

**Comment by dklymenk** [comment]
@TachibanaYoshino Thanks. That script worked flawlessly for me.
